import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import HeaderPage from '@/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mô hình cao cấp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body>
        <Providers>
          <HeaderPage/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
